### ISSUE TITLE
Application fails to load with Electron v1.1.0 (NOT COMPATIBLE YET!!! DO NOT USE!!!)

### ISSUE THREAD

**Issue by jediofthecode** [geeeeeeeeek/electronic-wechat#195]
#### Description

When opening the application, it hangs on the 'Starting app' dialog, and refuses to load. I have tried running it via terminal and receive no output. This started yesterday when I updated my version of electron.

#### Specifications

- Version of Electron v1.1.0
- Version of Node.js v6.1.0
- OS: Archlinux Kernel 4.5.4-1
- Architecture x86_64

**Comment by geeeeeeeeek** [comment]
### Electronic WeChat is NOT compatible with Electron v1.1.0 for now. 
@jediofthecode 

Please use previous versions such as 0.36.7 instead. This issue can be reproduced with the latest electron. I'll investigate my code when I get some time.

**Comment by geeeeeeeeek** [comment]
Good news! The problem has been solved. Actually it's caused by electron API changes, and there are a lot to keep up.

Luckily, we've got this app running on electron v1.1.0 successfully. I believe it's worth migrating to v1.1.0 for its performance improvement and a bunch of new features.

Electronic WeChat v1.3, which supports electron v1.1.0, will come tomorrow.

**Comment by jediofthecode** [comment]
Awesome ! thanks for the quick fix!

**Comment by geeeeeeeeek** [comment]
@jediofthecode 

Please checkout the `master` branch. Packed app will come tonight with release v1.3.0.
