### ISSUE TITLE
发送图片提示“图片上传失败，请检查你的网络 about”

### ISSUE THREAD

**Issue by kxz10323** [geeeeeeeeek/electronic-wechat#350]
#### Description

ubuntu16.04上发送图片提示“图片上传失败，请检查你的网络 about”，发送图片失败
#### Specifications
- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by xgdgsc** [comment]
archlinux下也一样，经常遇到文件上传下载失败的问题。

**Comment by geeeeeeeeek** [comment]
你们使用的 Electron 版本？ 新版本经常会有 regression 。

**Comment by xgdgsc** [comment]
1.4.0 ，是不是arch源里的electron更新后需要AUR重新打包。

**Comment by geeeeeeeeek** [comment]
@xgdgsc 建议 downgrade 到 release note 中声明支持的低版本 electron

**Comment by geeeeeeeeek** [comment]
或者使用我打包的应用

**Comment by kxz10323** [comment]
@geeeeeeeeek electron使用的是1.4.0版本，是因为这个版本太新了吗

**Comment by geeeeeeeeek** [comment]
@kxz10323 是

**Comment by hexchain** [comment]
Please either upgrade the code to be compatible with electron 1.4.0 or use a more strict version limit in `package.json`.

For now, `^1.3.4` matches `1.4.0` so I choose to use system package.

I'll update AUR package to enable electron-prebuilt, but that should not be considered good practice since 1. it may fail on some `.so`s because Arch is always so "new", and 2. we have a much saner self-built package that fits better in our system environment.

**Comment by hexchain** [comment]
Well, I just found out that `npm install` would download electron 1.4.1.

**Comment by xgdgsc** [comment]
我传了个纯bin的包https://aur.archlinux.org/packages/electronic-wechat-bin/先用着。
